# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f5394e335d2f5af48d04596ecf4f3be29a422bf8640334c44d3d7d58966e9e5aeb504a2717aaaa580d6f2696717c912919dc66f983a8bf2bac03865acc1c4d7e

test:
  secret_key_base: 117a2f7b15b2b7fa48a7542fe38903483b6c756e9f81070f80a1d2806dc3b66305b00c387039970107418faf6b28e2cdc70b578db159bd6e5602f35d84a22b09

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
